# Generated by Django 4.1.3 on 2022-11-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_builder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
